name: JCEF Javadoc Website

on:
  release:
    types: [published]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    
    - name: Dump env context
      env:
        ENV_CONTEXT: ${{ toJson(env) }}
      run: echo "$ENV_CONTEXT"

    - name: Checkout JCEF-BUILD
      uses: actions/checkout@v1
      with:
        path: jcef-build

    - name: Checkout JCEF
      run: |
        git clone https://github.com/chromiumembedded/java-cef jcef
        cd "$GITHUB_WORKSPACE/jcef"
        git apply --verbose ../patch/build-tools.patch
      shell: bash

    - name: Generate Docs
      if: success()
      run: |
        cd "$GITHUB_WORKSPACE/jcef/tools"
        ./make_docs.sh
      shell: bash

    - name: Build Pages
      if: success()
      run: |
        cd packaging
        ./gradlew --no-daemon -DBIN_ARTIFACT="$GITHUB_WORKSPACE/jcef/out/" -DARCH_DIST="" --info installDocsDist

    - name: Deploy Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.0.1
      with:
        target_branch: gh-pages
        build_dir: packaging/build/install/java-cef-build-docs
      env:
        GITHUB_PAT: ${{ secrets.TR_GITHUB_TOKEN }}  
